### ISSUE TITLE
Update PULL_REQUEST_TEMPLATE - remove "Any background context you want to provide?"

### ISSUE THREAD

**Issue by rymach** [codice/ddf#4752]
### Description

The Pull Request Template has several fields to be filled out, including a "Any background context you want to provide?" field.  This field appears to be rarely filled out... and typically, if there was any significant background information, it would already be covered in the description, where it would be more prominent. 

#### Expected behavior (if applicable):

People will provide all relevant background information in the description
### Version

N/A

**Comment by ethantmanns** [comment]
@rymach Can you fill out the template?

**Comment by coyotesqrl** [comment]
I've already commented on the PR - which should probably just be closed - but I'm willing to entertain the justifications for the change. Justifications which have not been added here. So please do.

**Comment by bdeining** [comment]
So, if we go through the open prs at this moment, we can see that this field is not used in the majority of cases. I'm confident that if it were quantified, the same would hold true.  If the field is not used, then why is it on the template?  I would think that the github issue would provide this.  I'm confused why this change is met with hostility and snarky comments, which are counterproductive.

**Comment by ethantmanns** [comment]
That's the kind of information that should be included in the Issue template here. I don't think it should be considered hostile for committers to ask contributors to fill out information on the Github Issue they open.

**Comment by coyotesqrl** [comment]
Agreed. Had that context and justification been provided on this Issue and its associated PR to begin with, it likely would have engendered a more reasonable discussion about whether it makes sense to reevaluate the presence of that field or to improve our training so that it is far more frequently filled.

N.B. Had the _Background Context_ field been filled in with a strong analysis and argument, it might have led to agreement that the _Background Context_ field is unnecessary; however, it should be obvious that this actually strengthens the counterargument: the _Background Context_ field is _clearly_ necessary and should be filled in _more often_ so that we are clear, complete, and transparent in our intentions and communications.

**Comment by bdeining** [comment]
@ethantmanns that's not the part that is considered hostile.
@coyotesqrl the point still stands that the background context can be provided in the issue itself.  I'm not finding it `clearly` how necessary it is on the PR.

**Comment by ethantmanns** [comment]
@bdeining And I think that's okay. It should be stated as the reason why the section should be removed here in the issue.

**Comment by coyotesqrl** [comment]
@bdeining I agree. Which is why when I was commenting on the PR I looked at the Issue to see if context had been clearly laid out here. It had not. It's necessary to put it somewhere. We can certainly agree on that.

Personally, I like to see it on the PR itself - even if it duplicates information from the Issue - but I am open to the notion of only leaving it on the Issue. But for that discussion to be had, the information must be somewhere.

**Comment by bdeining** [comment]
I don't disagree that the issue should have been filled out

**Comment by coyotesqrl** [comment]
Let's get this issue filled out, with the explanation and justifications for it, and we can discuss.

**Comment by rymach** [comment]
With the permission of everyone here I'd like to close this issue. I think it's low-priority enough that it doesn't deserve additional time.

**Comment by bdeining** [comment]
I think it's worth discussing as an improvement to the template, but certainly is not a high priority.

**Comment by millerw8** [comment]
I would like to highlight that anyone who sees this issue has value.  I kind of see the merits of this change, so I will add some meat to it based on the values I think it has.
